PR for merging Display Library
theam/haskell-do-display pull request #1
Opened 2017-02-27 20:47 UTC by KitFreddura

This is the first iteration of the display library for HaskellDO. This PR is meant to simply populate the repo with what I have done so far.

2017-02-27 21:27 UTC, NickSeagull requested changes

2017-02-27 21:27 UTC, NickSeagull commented on src/DisplayTypes.hs
> +data DisplayType
I think that this should not be that "open", we should have just:

- Text
- HTML
- SVG
- JS
- Image

We can add more types in the future, but we should not constraint users into adding their instance here.

2017-02-27 21:27 UTC, NickSeagull commented on src/Displayable.hs
> +instance (RecAll V.Identity r Show, ColumnHeaders r, AsVinyl r) => Displayable (Record r) where
This should be in another file, so we can import Displayable from there, and users can do the same.

2017-02-27 21:27 UTC, NickSeagull commented on src/Displayable.hs
> +-- Chart helper functions for storing and retrieving FilePath
Same thing with this

2017-02-28 01:12 UTC, KitFreddura commented
I broke the Record and Renderable Displayable instances into two separate files, and added the DisplayTypes you asked for, let me know if there's anything else 👍

2017-02-28 11:10 UTC, NickSeagull requested changes
Love the changes! I think that there's a typo, could you fix it? 😄

2017-02-28 11:10 UTC, NickSeagull commented on src/DisplayCharts.hs
> +  let filename = ".haskll-do-chart.svg"
typo?

2017-02-28 17:41 UTC, NickSeagull approved these changes

2017-02-28 17:41 UTC, NickSeagull commented
Nice, thanks!

2017-02-28 17:41 UTC, merged